services:



  database:
    image: postgres:16.4

    ports:
      - "5433:5432"
    volumes:
      - database_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: ElectronicsStore

volumes:
  database_data:


